//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Package/UiClick.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UiClick : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UiClick()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UiClick"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""01d393be-222a-4315-8002-0626316d8e6c"",
            ""actions"": [
                {
                    ""name"": ""UiLButtonDown"",
                    ""type"": ""Button"",
                    ""id"": ""84fb2a59-63f1-4d90-9238-6521b6d5940b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UiLButtonUp"",
                    ""type"": ""Button"",
                    ""id"": ""e9f3a5c4-3364-4bea-8c76-bdc5506bbc80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6aee13b9-f1af-45b8-886d-d83ea0354b5c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UiLButtonDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd70ebc-4d2e-48f6-a73f-b20a19d06547"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UiLButtonUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_UiLButtonDown = m_Player.FindAction("UiLButtonDown", throwIfNotFound: true);
        m_Player_UiLButtonUp = m_Player.FindAction("UiLButtonUp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_UiLButtonDown;
    private readonly InputAction m_Player_UiLButtonUp;
    public struct PlayerActions
    {
        private @UiClick m_Wrapper;
        public PlayerActions(@UiClick wrapper) { m_Wrapper = wrapper; }
        public InputAction @UiLButtonDown => m_Wrapper.m_Player_UiLButtonDown;
        public InputAction @UiLButtonUp => m_Wrapper.m_Player_UiLButtonUp;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @UiLButtonDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUiLButtonDown;
                @UiLButtonDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUiLButtonDown;
                @UiLButtonDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUiLButtonDown;
                @UiLButtonUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUiLButtonUp;
                @UiLButtonUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUiLButtonUp;
                @UiLButtonUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUiLButtonUp;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UiLButtonDown.started += instance.OnUiLButtonDown;
                @UiLButtonDown.performed += instance.OnUiLButtonDown;
                @UiLButtonDown.canceled += instance.OnUiLButtonDown;
                @UiLButtonUp.started += instance.OnUiLButtonUp;
                @UiLButtonUp.performed += instance.OnUiLButtonUp;
                @UiLButtonUp.canceled += instance.OnUiLButtonUp;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnUiLButtonDown(InputAction.CallbackContext context);
        void OnUiLButtonUp(InputAction.CallbackContext context);
    }
}
